name: Test real GitHub Actions cache service

on:
  schedule:
    - cron: '14 7 * * *' # 6:07AM PST / 7:07AM PDT
  workflow_dispatch:

jobs:
  tests:
    strategy:
      matrix:
        include:
          - node: 20 # LTS
            os: ubuntu-22.04

    runs-on: ${{ matrix.os }}

    env:
      WIREIT_LOGGER: 'quiet-ci'

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      # The goal here is to always run the full caching test suite against the
      # live GitHub Actions Cache service, even if none of our code has changed,
      # in case something changed on the backend.
      #
      # So, slightly confusingly, although we disable caching of the top-level
      # test script below, we do need the runner environment set up to allow
      # GitHub caching.
      - uses: google/wireit@setup-github-actions-caching/v2

      - run: npm ci
      - run: npm run test:cache-github-real
        env:
          WIREIT_CACHE: none
